import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemesProvider } from "./theme/theme-provider";
import { ToggleTheme } from "./theme/theme-control";
import { ApolloProviderClient } from "./graphql/provider";
import { RecoilRootProvider } from "./state-management/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRootProvider>
          <ApolloProviderClient>
            <ThemesProvider>
              {/* <ToggleTheme /> */}
              {children}
            </ThemesProvider>
          </ApolloProviderClient>
        </RecoilRootProvider>
      </body>
    </html>
  );
}
